#!/bin/bash
ip_address=$(hostname -I | cut -d' ' -f1)

cleanBuild() {
	echo "Removendo arquivos compilados de 'static/'"
	rm -rf static/*
}

case $1 in
    build)
        echo "Construindo aplicativo..."

        # Para comprimir os estáticos deve-se desabilitar o modo debug.
        export DEBUG_MODE=False

        cleanBuild

        echo "Coletando arquivos estáticos..."
        python manage.py collectstatic -c --no-input

    ;;
    *)  
        echo "Iniciando Mega Forms"

        python manage.py runserver 0.0.0.0:8000
    ;;
esac