#!/bin/bash
ip_address=$(hostname -I | cut -d' ' -f1)

cleanBuild() {
	echo "Removendo arquivos compilados de 'static/'"
	rm -rf static/*
}

case $1 in
    build)
        echo "Construindo aplicativo..."

        # Para comprimir os estáticos deve-se desabilitar o modo debug.
        export DEBUG_MODE=False

        cleanBuild

        echo "Coletando arquivos estáticos..."
        python manage.py collectstatic -c --no-input

    ;;
    *)  
        tput setaf 32
        echo "Endereço IP capturado: $ip_address"
        echo "Iniciando Mega Forms"
        tput setaf 37

        cleanBuild
        
        tput setaf 32
        echo "Sistema acessível por toda a Intranet"
        tput setaf 37

        python manage.py runserver $ip_address:8000
    ;;
esac