##BaseViews
from questionario.views.baseViews.BasePermissoesView import BasePermissoesView

#Páginas
from questionario.views.site.MegaFormsIndexView import MegaFormsIndexView
from questionario.views.site.EquipeView import EquipeView
from questionario.views.site.NoticiasView import NoticiasView
from questionario.views.site.SobreView import SobreView
from questionario.views.site.RepositorioView import RepositorioView
from questionario.views.site.PoliticaPrivacidadeView import PoliticaPrivacidadeView

##Questionários
from questionario.views.questionarios.QuestionariosIndexView import QuestionariosIndexView
from questionario.views.questionarios.QuestionariosDetailView import QuestionariosDetailView
from questionario.views.questionarios.RespostasDetailView import RespostasDetailView
###
from questionario.views.relatorios.ExportRespostasView import ExportRespostasView
from questionario.views.relatorios.RelatorioQuestionarioView import RelatorioQuestionarioView

from questionario.views.rest.QuestionarioRestView import QuestionarioRestView
from questionario.views.rest.RelatorioQuestionarioRestView import RelatorioQuestionarioRestView