# Generated by Django 5.0.6 on 2024-05-31 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQuestionario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, choices=[(0, 'Escolha'), (1, 'Multipla Escolha'), (2, 'Texto')], default=0, null=True, verbose_name='Tipos de questão')),
                ('descricao', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição do Item do Questionário')),
                ('ativo', models.BooleanField(default=True, editable=False, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Item do Questionário',
                'verbose_name_plural': 'Itens do Questionário',
                'ordering': ['id', 'ativo'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=255, verbose_name='Título da Notícia:')),
                ('img', models.ImageField(blank=True, null=True, upload_to='noticias', verbose_name='Imagem da Notícia')),
                ('subtitulo', models.TextField(blank=True, max_length=280, null=True, verbose_name='Subtítulo da Notícia')),
                ('noticia', models.TextField(verbose_name='Corpo da Notícia')),
                ('ativo', models.BooleanField(default=True, editable=False, verbose_name='Ativo?')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuemRespondeu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.TextField(max_length=100, verbose_name='Sobrenome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('cidade', models.TextField(max_length=100, verbose_name='Cidade')),
                ('cargo', models.TextField(max_length=100, verbose_name='Cargo')),
                ('dataAniversario', models.DateField(blank=True, null=True, verbose_name='Data de Aniversário')),
                ('ativo', models.BooleanField(default=True, editable=False, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Quem Respondeu',
                'verbose_name_plural': 'Quem Respondeu',
                'ordering': ['id', 'ativo'],
            },
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=255, verbose_name='Título do Slide')),
                ('subtitulo', models.TextField(blank=True, max_length=280, null=True, verbose_name='Subtítulo do Slide')),
                ('img', models.ImageField(upload_to='slideshow', verbose_name='Imagem do Slide')),
                ('ativo', models.BooleanField(default=True, editable=False, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Slideshow',
                'verbose_name_plural': 'Slideshow',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo', models.IntegerField(choices=[(0, 'Documento'), (1, 'Link')], default=0, verbose_name='Tipos de Documento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['id', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='OpcoesItemQuestionario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField(max_length=100, verbose_name='Resposta')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionario.itemquestionario', verbose_name='Pergunta do Questionario')),
            ],
            options={
                'verbose_name': 'Opção de Resposta',
                'verbose_name_plural': 'Opções de Respostas',
                'ordering': ['id'],
                'unique_together': {('valor', 'pergunta')},
            },
        ),
        migrations.CreateModel(
            name='ItemDependente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True, editable=False, verbose_name='Ativo?')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pergunta', to='questionario.itemquestionario', verbose_name='Pergunta Secundária')),
                ('perguntaChave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguntaChave', to='questionario.itemquestionario', verbose_name='Pergunta Principal')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionario.opcoesitemquestionario', verbose_name='Opção')),
            ],
            options={
                'verbose_name': 'Item Dependente',
                'verbose_name_plural': 'Itens Dependentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Documento:')),
                ('descricao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição do Documento')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='repositorio/', verbose_name='Arquivo')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quemCadastrou', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.pessoa', verbose_name='Quem Cadastrou')),
                ('tipo', models.ForeignKey(help_text='Guias, Cartilhas, Manuais, Gestão AF', on_delete=django.db.models.deletion.PROTECT, to='questionario.tipodocumento', verbose_name='Tipo do Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['dataCadastro', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoQuestionario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255, verbose_name='Nome do Questionário:')),
                ('descricao', models.TextField(blank=True, max_length=280, null=True, verbose_name='Descrição do Questionário')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('quemCadastrou', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Quem Cadastrou')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
                'ordering': ['id', 'nome', 'dataCadastro'],
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField(max_length=2800, verbose_name='Resposta')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionario.itemquestionario', verbose_name='Pergunta do Questionario')),
                ('quemRespondeu', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='questionario.quemrespondeu', verbose_name='Quem Respondeu')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionario.tipoquestionario', verbose_name='Nome do Questionario')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='itemquestionario',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionario.tipoquestionario', verbose_name='Nome do Questionario'),
        ),
    ]
