# Generated by Django 4.1.1 on 2023-09-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quemrespondeu',
            name='dataAniversario',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aniversário'),
        ),
    ]
