# Generated by Django 5.0.6 on 2024-05-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quemrespondeu',
            name='dataAniversario',
        ),
        migrations.AddField(
            model_name='quemrespondeu',
            name='idade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade de quando Respondeu'),
        ),
        migrations.AlterField(
            model_name='itemquestionario',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(0, 'Objetiva'), (1, 'Multipla Escolha'), (2, 'Discursiva')], default=0, null=True, verbose_name='Tipos de questão'),
        ),
        migrations.AlterField(
            model_name='quemrespondeu',
            name='cargo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='quemrespondeu',
            name='cidade',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='quemrespondeu',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='quemrespondeu',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
