# Generated by Django 5.0.6 on 2024-06-03 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_remove_quemrespondeu_dataaniversario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quemrespondeu',
            name='sexo',
            field=models.IntegerField(blank=True, choices=[(0, 'Feminino'), (1, 'Masculino')], default=0, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='itemquestionario',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(0, 'Objetiva'), (1, 'Multipla Escolha'), (2, 'Discursiva'), (3, 'Associativa')], default=0, null=True, verbose_name='Tipos de questão'),
        ),
        migrations.CreateModel(
            name='ItemAssociativo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField(max_length=100, verbose_name='Resposta')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionario.opcoesitemquestionario', verbose_name='Opção Associativa')),
            ],
            options={
                'verbose_name': 'Opção Associativa',
                'verbose_name_plural': 'Opções Associativas',
                'ordering': ['id'],
                'unique_together': {('valor', 'opcao')},
            },
        ),
    ]
