# Generated by Django 5.0.6 on 2024-06-03 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0003_quemrespondeu_sexo_alter_itemquestionario_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemassociativo',
            name='opcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionario.itemquestionario', verbose_name='Opção Associativa'),
        ),
        migrations.AlterField(
            model_name='itemassociativo',
            name='valor',
            field=models.TextField(max_length=5000, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='opcoesitemquestionario',
            name='valor',
            field=models.TextField(max_length=500, verbose_name='Resposta'),
        ),
    ]
