# Generated by Django 5.0.6 on 2024-06-06 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0006_quemrespondeu_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quemrespondeu',
            name='vinculo',
            field=models.IntegerField(blank=True, choices=[(0, 'Concursado'), (1, 'Contratado'), (2, 'Não Respondeu')], default=0, null=True, verbose_name='Vinculo'),
        ),
        migrations.CreateModel(
            name='VinculoQuestionario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True, editable=False, verbose_name='Ativo?')),
                ('questionarioPos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionarioPos', to='questionario.tipoquestionario', verbose_name='Nome do Questionario')),
                ('questionarioPre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionarioPre', to='questionario.tipoquestionario', verbose_name='Nome do Questionario')),
            ],
            options={
                'verbose_name': 'Vínculo do Questionário',
                'verbose_name_plural': 'Vínculos dos Questionários',
                'ordering': ['id', 'ativo'],
            },
        ),
    ]
