# Generated by Django 5.0.6 on 2024-06-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0007_alter_quemrespondeu_vinculo_vinculoquestionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCorreto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.BooleanField(default=False, verbose_name='Correto?')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionario.itemquestionario', verbose_name='Opção Associativa')),
            ],
            options={
                'verbose_name': 'Opção Correta',
                'verbose_name_plural': 'Opções Corretas',
                'ordering': ['id'],
                'unique_together': {('valor', 'opcao')},
            },
        ),
    ]
