# Generated by Django 5.0.6 on 2024-06-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0008_itemcorreto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcorreto',
            name='valor',
            field=models.TextField(max_length=5000, verbose_name='Resposta'),
        ),
    ]
