# Generated by Django 4.1.1 on 2023-04-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nomeCompleto', 'ativo'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddField(
            model_name='pessoa',
            name='contato',
            field=models.CharField(blank=True, default=None, help_text='Fone de contato com DDD (63) 98765-4321', max_length=255, null=True, verbose_name='Fone de contato'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, choices=[(None, 'Ainda não verificado'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=2, null=True, verbose_name='Sexo'),
        ),
    ]
