# Generated by Django 4.1.1 on 2023-09-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, choices=[(None, 'Ainda não configurado'), ('1', 'Estagiário(a)'), ('2', 'Desenvolvedor'), ('3', 'Agente')], max_length=4, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem que será mostrada em seu Perfil', null=True, upload_to='imagem/perfil', verbose_name='Imagem de Perfil'),
        ),
    ]
