# Generated by Django 4.1.1 on 2023-12-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteCecane', '0003_tipodocumento_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['id', 'nome'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='repositorio/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='noticias', verbose_name='Imagem da Notícia'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='img',
            field=models.ImageField(upload_to='slideshow', verbose_name='Imagem do Slide'),
        ),
    ]
