# Generated by Django 4.1.1 on 2024-03-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteCecane', '0004_alter_tipodocumento_options_tipodocumento_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Documento'), (1, 'Link')], default=0, verbose_name='Tipos de Documento'),
        ),
    ]
