# Generated by Django 4.1.1 on 2024-04-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteCecane', '0006_alter_tipoquestionario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcoesitemquestionario',
            name='valor',
            field=models.TextField(max_length=100, verbose_name='Resposta'),
        ),
    ]
