# Generated by Django 4.1.1 on 2024-04-19 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AGF', '__first__'),
        ('siteCecane', '0007_alter_opcoesitemquestionario_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField(max_length=100, verbose_name='Resposta')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, editable=False, verbose_name='Ativo?')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AGF.escola', verbose_name='Escola')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteCecane.itemquestionario', verbose_name='Pergunta do Questionario')),
                ('quemCadastrou', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Quem Cadastrou')),
                ('quemRespondeu', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='siteCecane.quemrespondeu', verbose_name='Quem Respondeu')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteCecane.tipoquestionario', verbose_name='Nome do Questionario')),
            ],
            options={
                'verbose_name': 'Resposta de Questionário',
                'verbose_name_plural': 'Respostas de Questionários',
                'ordering': ['id'],
            },
        ),
    ]
